name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  dist:
    name: Make distribution using Dist::Zilla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache ~/perl5
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist-locallib
          path: ~/perl5
      - name: Perl version
        run: |
          perl -v
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install Dist::Zilla
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n Dist::Zilla
          dzil authordeps --missing | cpanm -n
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          dzil build --in build-dir
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./build-dir
  test:
    needs: dist
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # bash on macos and linux
        # powershell on windows + strawberry perl
        # msys2 {0} on windows + msys2
        shell: >-
          ${{   fromJSON( '["", "bash {0}"]'       )[ matrix.os == 'ubuntu-latest'  || matrix.os == 'macos-11'     ]
          }}${{ fromJSON( '["", "powershell {0}"]' )[ matrix.os == 'windows-latest' && matrix.dist == 'strawberry' ]
          }}${{ fromJSON( '["", "msys2 {0}"]'      )[ matrix.os == 'windows-latest' && matrix.dist == 'msys2'      ] }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version: ['5.8', '5.20', '5.30', '5.34']
        alien-install-type: [ 'system', 'share' ]
        include:
          - perl-version: '5.34'
            os: windows-latest
            dist: strawberry
            alien-install-type: 'share'
          - perl-version: '5.34'
            os: windows-latest
            dist: msys2
            alien-install-type: 'system'
          - perl-version: '5.34'
            os: windows-latest
            dist: msys2
            alien-install-type: 'share'
          - perl-version: '5.34'
            os: macos-11
            alien-install-type: 'system'
          - perl-version: '5.34'
            os: macos-11
            alien-install-type: 'share'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }} with install-type ${{ matrix.alien-install-type }}, dist ${{ matrix.dist }}

    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      # Note CMake is already installed in virtual-environments.

      # Setup system Ninja
      - name: Setup system Ninja (apt)
        if: runner.os == 'Linux' && matrix.alien-install-type == 'system'
        run: |
          sudo apt-get -y update && sudo apt-get install -y ninja-build
      - name: Setup system Ninja (homebrew)
        if: runner.os == 'macOS' && matrix.alien-install-type == 'system'
        run: |
          brew install ninja
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows' && matrix.dist == 'msys2'
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-perl
            mingw-w64-x86_64-cmake
      - name: Set up Ninja (MSYS2/MinGW pacman)
        if: runner.os == 'Windows' && matrix.dist == 'msys2' && matrix.alien-install-type == 'system'
        shell: msys2 {0}
        run: |
          pacman -S --needed --noconfirm mingw-w64-x86_64-ninja

      # Setup Perl
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest' && matrix.dist == 'strawberry'
        with:
          distribution: 'strawberry'

      - run: perl -V
      - name: Install cpanm
        if: runner.os == 'Windows' && matrix.dist == 'msys2'
        run:
          yes | cpan -T App::cpanminus || true

      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps .

      - name: Set ALIEN_INSTALL_TYPE
        shell: bash
        run: |
          echo "ALIEN_INSTALL_TYPE=${{ matrix.alien-install-type }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cpanm --verbose --test-only .
